services:
  database:
    image: postgres:14-alpine
    container_name: auction-db
    restart: unless-stopped
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'auction-db'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -d auction-db -U postgres -h 127.0.0.1
      interval: 1s